version: "3.9"

networks:
  anivoy-shared-net:
    external: true

services:
  scene:
    build:
      context: .
      target: development
    container_name: anivoy-scene-service
    ports:
      - "7200:7200"
    env_file:
      - .env
    depends_on:
      - postgis
      - redis
    restart: unless-stopped
    networks:
      - anivoy-shared-net
  